
FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /app/task-backend ./cmd/main.go

FROM alpine:latest
WORKDIR /app
RUN apk --no-cache add ca-certificates tzdata && \
    update-ca-certificates
COPY --from=builder /app/task-backend .
EXPOSE 8080
CMD ["./task-backend"]
