pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS = credentials('docker-credentials')
        IMAGE_BACKEND  = "gabrielcq/task-backend"
        IMAGE_FRONTEND = "gabrielcq/task-frontend"
        TAG            = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout code') {
            steps {
                checkout scm
            }
        }

        stage('Build backend image') {
            steps {
                dir('task-backend') {
                    bat "docker build -t ${IMAGE_BACKEND}:${TAG} -t ${IMAGE_BACKEND}:latest ."
                }
            }
        }

        stage('Build frontend image') {
            steps {
                dir('task-frontend') {
                    bat "docker build -t ${IMAGE_FRONTEND}:${TAG} -t ${IMAGE_FRONTEND}:latest ."
                }
            }
        }

        stage('Login to docker hub') {
            steps {
                bat "echo %DOCKER_CREDENTIALS_PSW% | docker login -u %DOCKER_CREDENTIALS_USR% --password-stdin"
            }
        }

        stage('Push images to docker hub') {
            steps {
                bat "docker push ${IMAGE_BACKEND}:latest"
                bat "docker push ${IMAGE_FRONTEND}:latest"
            }
        }

        stage('Deploy application') {
            steps {
                bat 'docker compose -f deployment/docker-compose.yml down --remove-orphans || echo "No containers to remove"'
                bat 'docker compose -f deployment/docker-compose.yml up -d --build'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completado'
        }
        failure {
            echo 'Pipeline falló'
        }
        always {
            bat 'docker logout' || true
        }
    }
}

