pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS = credentials('docker-credentials')
        IMAGE_BACKEND      = "gabrielcq/task-backend"
        IMAGE_FRONTEND     = "gabrielcq/task-frontend"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Backend') {
            steps {
                bat "docker build -t ${IMAGE_BACKEND}:latest -f task-backend/Dockerfile task-backend/"
            }
        }

        stage('Build Frontend') {
            steps {
                bat "docker build -t ${IMAGE_FRONTEND}:latest -f task-frontend/Dockerfile task-frontend/"
            }
        }

        stage('Login Docker Hub') {
            steps {
                bat "echo %DOCKER_CREDENTIALS_PSW% | docker login -u %DOCKER_CREDENTIALS_USR% --password-stdin"
            }
        }

        stage('Push Images') {
            steps {
                bat "docker push ${IMAGE_BACKEND}:latest"
                bat "docker push ${IMAGE_FRONTEND}:latest"
            }
        }

        stage('Deploy') {
            steps {
                bat 'docker compose -f deployment/docker-compose.yml down --remove-orphans || true'
                bat 'docker compose -f deployment/docker-compose.yml up -d --build'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completado con éxito'
        }
        failure {
            echo 'Pipeline falló'
        }
        always {
            bat 'docker logout || true'
        }
    }
}